version: "3"

services:
  mysql-db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 56147865
       MYSQL_DATABASE: produto
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
  app:
    image: rlouzano/dashboard_java:v1
    container_name: java
    depends_on:
      - mysql-db
    environment:
      spring.datasource.url: jdbc:mysql://mysql-db:3306/produto?useTimezone=true&serverTimezone=UTC
    ports:
      - "9090:8080"